### ISSUE TITLE
Jewish festival start and finishing times including fast times API

### ISSUE THREAD

**Issue by NSWJBD** [hebcal/hebcal#121] opened 2016-01-19 22:28 UTC
Hi, We are using your API for our APP that we are developing. The Shabbat times and parashot are great - and we love it but we also want to display start and finish times for all major Jewish fesitvals and fasts which currently doesn't exist that we can tell. Can you help? thanks

**Comment by mjradwin** [comment] 2016-01-25 20:06
This is a duplicate of feature request #100. We do display start ("Candle lighting") and finish ("Havdalah") for all major festivals. We do not yet support start/end times for minor fasts.

**Comment by mjradwin** [comment] 2020-12-21 16:09
We've added support for fast start and end times to the Javascript implementation of Hebcal, which now powers the hebcal.com website.

Minor fasts begin at Alot HaShachar (sun is 16.1° below the horizon in the morning) and end when 3 medium-sized stars are observable in the night sky (sun is 7.083° below the horizon in the evening).

We don't plan to backport these fast start/end times to C.

**Closed by mjradwin** 2020-12-21 16:09 UTC
