### ISSUE TITLE
test suite fails for big endian architectures

### ISSUE THREAD

**Issue by sjpotter** [hebcal/hebcal#170] opened 2019-01-20 21:16 UTC
4.16 has been uploaded to Debian, but is failing to build (test suite fails) for big endian architectures.  i.e. mips64 fails (big endian) while mips64el (little endian) passes.

**Comment by sjpotter** [comment] 2019-01-20 21:17
also, test suite failures say "Please report to hebcal-bugs@sadinoff.com" but that seems to be an artifact as email no longer works.

**Comment by mjradwin** [comment] 2019-01-20 22:02
Ok, I will figure out how to get my hands on a big endian Linux box and reproduce. I have been building on Mac and DigitalOcean ubuntu for the past 6+ years but have not been thinking about other architectures.

**Comment by mjradwin** [comment] 2019-01-21 05:49
Crash confirmed on QEMU mips big endian. It's happening in timelib with the built-in timezonedb. Working on a fix but it may be a week or more.

**Comment by mjradwin** [comment] 2019-02-11 05:10
I haven't made any progress on this. It's on my radar, I just haven't had
time to do it.

**Comment by barak** [comment] 2019-03-12 18:32
I'm the person who adopted the debian package and uploaded the latest version. If you make any progress on this, or need help, please do let me know, preferably by email to the relevant debian bug report: mailto:919868@bugs.debian.org. I'd like to get 4.16+ into the (currently frozen) next stable release, and that is blocked by this particular issue.

Ref: https://bugs.debian.org/919868

**Comment by mjradwin** [comment] 2019-04-14 01:40
I just added b9f143a16e3d8030eb9ab1143fd99eb6c54dfcb6 which disables the 2 failing test suite problems on big endian. This doesn't actually fix the big-endian issue with timelib, but I believe it's enough to get hebcal working on big endian for everything that doesn't involve sunrise/sunset/candle-lighting.

**Comment by barak** [comment] 2019-04-15 10:30
> So, come up to the lab,
> and see what's on the slab!
> I see you shiver with antici _[long pause]_ pation.
> But maybe the rain
> isn't really to blame,
> so I'll remove the cause...
> _[chuckles]_ but not the symptom.

—Dr. Frank N. Furter

**Comment by barak** [comment] 2019-04-16 13:26
To be serious, I haven't looked carefully, but could a more recent version of https://github.com/derickr/timelib/network be used? Perhaps even tracked as a submodule? The file `parse_tz.c` has had a bunch of changes there, including in particular adding some logic related to endianity.

**Comment by mjradwin** [comment] 2019-04-17 04:53
I tried pulling in the new timelib a couple of months ago. It turns out the
sunrise/sunset calculations have changed such that all historical candle
lighting times may differ by 1-2 minutes. I did not have time to
investigate why or how to find a way to get the existing sunset behavior.

In general I would prefer to avoid spurious changes to candle lighting
times as this will cause lots of user support inquiries. Changing candle
lighting times for a good reason (e.g. if the current times were somehow
inaccurate and upgrading timelib made them more accurate) would be
acceptable. However, I don't have confidence or knowledge either way, so I
am avoiding picking up the new timelib until I could know.

I believe the vast majority of the *nix and Debian world is using little
endian, which is why I opted for the principle of least change in my recent
big endian workaround.

--

**Comment by sjpotter** [comment] 2019-04-17 04:57
see php's timelib, they have big/little endian helper functions for parsing the db.

**Comment by mjradwin** [comment] 2019-04-17 05:15
Yes, I believe we're already using php's timelib. As far as I know, derickr/timelib and php's timelib are the exact same module.

**Comment by sjpotter** [comment] 2019-04-17 15:27
might it be worth filing an issue there with your observations about the change?

**Comment by mjradwin** [comment] 2019-04-28 00:37
Updated timelib as part of v4.18 and commit d233609cbf1bbe67dea1985f07667441919ed8cf

**Comment by barak** [comment] 2019-08-04 15:47
I'm still getting test failures on some architectures on the Debian autobuilders. See https://buildd.debian.org/status/package.php?p=hebcal

**Comment by mjradwin** [comment] 2019-08-04 16:07
I see the segmentation faults in the full logfile. Apparently bringing in
the latest timelib wasn't sufficient to solve the problem. There must be a
big-endian defect elsewhere in Hebcal.

Do you have a big-endian host that I could ssh into so I can reproduce the
crash and then rework whatever part of the code is defective? I tried using
a mips simulator on Mac but this wasn't very effective, and I couldn't see
how to get a big-endian VM from my favorite cloud hosting providers
(DigitalOcean, AWS).

**Comment by barak** [comment] 2019-08-05 06:37
Would any of the "public access" machines listed on https://db.debian.org/machines.cgi work for you? They are intended for exactly this sort of thing. If access requires an email of introduction from me (I don't think it does) I'd be happy to send one.

**Comment by mjradwin** [comment] 2019-08-05 20:11
Yes, I think that would work great. Can you send me a pointer to
documentation about how I might get an account on one of those systems?

**Comment by barak** [comment] 2019-08-06 09:18
If you tell me exactly what to do, I can run something on one of them for you. Or, email me the info mentioned on https://dsa.debian.org/doc/guest-account/ and I'll sign it and forward it on.

**Comment by mjradwin** [comment] 2019-09-29 14:52
I received guest access to a big-endian Debian porter machine and I have started to debug this issue. In fact, there's a crash in timelib - the function `read_32bit_header` in `parse_tz.c` isn't functioning correctly. I need to debug further.

While debugging this, I did push a change 41909842e4914f9859a61bf200119de4eb22b081 that only uses the timezonedb if the candle-lighting or experimental zmanim options are being used. This fixes the crash on big-endian for the simple uses of hebcal that don't involve locations and optimizes hebcal on all architectures a bit.

Reopening this bug until it's really fixed.

Shana Tova!

**Comment by mjradwin** [comment] 2019-09-29 15:28
Tracked down the issue. On **sparc64** and **mips64** we need to check
`#if __BYTE_ORDER == __BIG_ENDIAN`
instead of 
`#if defined(__BIG_ENDIAN__)`
Adding this additional check to `parse_tz.c` fixes the long-standing issue.
I am closing this bug and will release in hebcal-4.19.

**Closed by mjradwin** 2019-09-29 15:28 UTC

**Comment by barak** [comment] 2019-09-29 16:48
Shana Tovah indeed.
