### ISSUE TITLE
CORS Is Disabled

### ISSUE THREAD

**Issue by mjfeintuch** [hebcal/hebcal#154] opened 2018-08-22 04:03 UTC
When I try to access the REST API from a HTML/JS page, the console shows that: `...has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by mjradwin** [comment] 2018-08-22 10:42
I can't reproduce this bug. When I make an API request, I see the header.

$ **curl -v -o /dev/null 'https://www.hebcal.com/hebcal/?v=1&cfg=json&maj=on&min=on&mod=on&nx=on&year=now&month=x&ss=on&mf=on&c=on&geo=geoname&geonameid=3448439&m=50&s=on'**
...
Date: Wed, 22 Aug 2018 10:39:59 GMT
Server: Apache/2.4.29 (Ubuntu)
**Access-control-allow-origin:** *
Cache-control: max-age=86400
P3P: policyref="https://www.hebcal.com/w3c/p3p.xml", CP="ALL CURa ADMa DEVa TAIa PSAa OUR BUS IND PHY ONL COM NAV INT PRE"
Content-Type: application/json; charset=UTF-8
X-Varnish: 310207008
Age: 0
Via: 1.1 varnish (Varnish/5.2)
Accept-Ranges: bytes
Transfer-Encoding: chunked
Connection: keep-alive

**Comment by mjfeintuch** [comment] 2018-08-22 11:17
Did you make a request using a server? I am trying to make a fetch() within a JavaScript doc that is embedded in HTML. I then try to open the HTML locally in Chrome.

If you still can't reproduce the bug, I'll put up my code. (I'm just mobile now).

**Comment by mjradwin** [comment] 2018-08-27 19:55
Closing this since we see the CORS header and can't seem to reproduce the issue you mentioned.

**Closed by mjradwin** 2018-08-27 19:55 UTC
Labels: invalid
