### ISSUE TITLE
Shushan Purim when it's Purim Meshulash

### ISSUE THREAD

**Issue by nkasimer** [hebcal/hebcal#212] opened 2021-03-01 16:16 UTC
It seems that when the 15th of Adar falls on Shabbat, Hebcal treats Shushan Purim as being on Sunday and not on Shabbat.  While some Purim stuff is pushed off to Sunday, there are still Shushan Purim things that happen on Shabbat (e.g. Al HaNisim).  So when Shushan Purim is on Shabbat Hebcal shows the leyning for Sunday as being the Purim leyning--but in places that celebrate Shushan Purim this is actually read on Shabbat, not on Sunday.

Possible solutions would be to say that, in years like this, both Shabbat and Sunday are Shushan Purim, with leyning only returning for the one on Shabbat (possibly with the haftarah read in places with Shushan Purim, which is the one for Zakhor I believe).  Or to have Shabbat be Shushan Purim, and Sunday listed as "Purim Meshulash".

**Comment by mjradwin** [comment] 2022-09-30 18:04
Thanks for the bug report. Our apologies for the delay in responding.

This appears to be a duplicate of issue #20 (dating back to 2005).

I like the recommendation to have Shabbat be listed as "Shushan Purim", and Sunday listed as "Purim Meshulash".

@dsadinoff, what do you think?

**Comment by mjradwin** [comment] 2022-10-02 17:39
Fixed in v5.1.0

**Closed by mjradwin** 2022-10-02 17:39 UTC
